CREATE OR REPLACE NOTIFICATION INTEGRATION snowpipe_event
    ENABLED = true
    TYPE = QUEUE
    NOTIFICATION_PROVIDER = AZURE_STORAGE_QUEUE
    AZURE_STORAGE_QUEUE_PRIMARY_URI = '' -- get URL from storage account queue section
    AZURE_TENANT_ID = ''

DESCRIBE NOTIFICATION INTEGRATION snowpipe_event;